on: pull_request
name: Create an issue on all pull request events
jobs:
  createAnIssue:
    name: Create an issue
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Create an issue
      uses: JasonEtco/create-an-issue@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
